# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Current working directory
[directory]
truncation_length = 2
home_symbol = 'ğŸ '

##
## Toggle modules
##

# Kubernetes config, context, namespace
[kubernetes]
disabled = false

# Insert a line break, making the prompt single line
[line_break]
disabled = true

# Package versions for multiple languages
[package]
disabled = true

[terraform]
disabled = true

